<?php
/**
 * LLMs TXT Generator Service
 *
 * Generates the llms.txt file content with store data
 */
declare(strict_types=1);

namespace SystemSixtyFour\LlmsTxtGenerator\Model;

use Magento\Catalog\Api\CategoryRepositoryInterface;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Catalog\Model\ResourceModel\Category\CollectionFactory as CategoryCollectionFactory;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory as ProductCollectionFactory;
use Magento\Cms\Model\ResourceModel\Page\CollectionFactory as CmsPageCollectionFactory;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Filesystem;
use Magento\Framework\Stdlib\DateTime\DateTime;
use Magento\Store\Model\StoreManagerInterface;
use Psr\Log\LoggerInterface;

class Generator
{
    private const LLMS_TXT_FILENAME = 'llms.txt';

    private Config $config;
    private ProductCollectionFactory $productCollectionFactory;
    private CategoryCollectionFactory $categoryCollectionFactory;
    private CmsPageCollectionFactory $cmsPageCollectionFactory;
    private StoreManagerInterface $storeManager;
    private Filesystem $filesystem;
    private DateTime $dateTime;
    private LoggerInterface $logger;

    public function __construct(
        Config $config,
        ProductCollectionFactory $productCollectionFactory,
        CategoryCollectionFactory $categoryCollectionFactory,
        CmsPageCollectionFactory $cmsPageCollectionFactory,
        StoreManagerInterface $storeManager,
        Filesystem $filesystem,
        DateTime $dateTime,
        LoggerInterface $logger
    ) {
        $this->config = $config;
        $this->productCollectionFactory = $productCollectionFactory;
        $this->categoryCollectionFactory = $categoryCollectionFactory;
        $this->cmsPageCollectionFactory = $cmsPageCollectionFactory;
        $this->storeManager = $storeManager;
        $this->filesystem = $filesystem;
        $this->dateTime = $dateTime;
        $this->logger = $logger;
    }

    /**
     * Generate llms.txt file
     *
     * @param int|null $storeId
     * @return bool
     */
    public function generate(?int $storeId = null): bool
    {
        try {
            if (!$this->config->isEnabled($storeId)) {
                $this->logger->info('LLMs TXT Generator: Module is disabled');
                return false;
            }

            $content = $this->buildContent($storeId);
            $this->writeFile($content);

            $this->logger->info('LLMs TXT Generator: File generated successfully');
            return true;

        } catch (\Exception $e) {
            $this->logger->error('LLMs TXT Generator: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Build the llms.txt content
     */
    private function buildContent(?int $storeId = null): string
    {
        $lines = [];

        // Header
        $lines[] = '# LLMs.txt - AI Crawler Information';
        $lines[] = '# Generated by SystemSixtyFour LLMs TXT Generator for Magento 2';
        $lines[] = '# Generated at: ' . $this->dateTime->gmtDate('Y-m-d H:i:s') . ' UTC';
        $lines[] = '';

        // Company Information
        $companyName = $this->config->getCompanyName($storeId);
        if ($companyName) {
            $lines[] = '# Company: ' . $companyName;
        }

        $companyDescription = $this->config->getCompanyDescription($storeId);
        if ($companyDescription) {
            $lines[] = '> ' . $this->formatDescription($companyDescription);
        }

        $additionalInfo = $this->config->getAdditionalInfo($storeId);
        if ($additionalInfo) {
            $lines[] = '';
            $lines[] = '## Additional Information';
            $lines[] = $this->formatDescription($additionalInfo);
        }

        $lines[] = '';

        // Entity Sections
        $entityTypes = $this->config->getEntityTypes($storeId);

        if (in_array('cms_pages', $entityTypes)) {
            $lines = array_merge($lines, $this->buildCmsPagesSection($storeId));
        }

        if (in_array('products', $entityTypes)) {
            $lines = array_merge($lines, $this->buildProductsSection($storeId));
        }

        if (in_array('categories', $entityTypes)) {
            $lines = array_merge($lines, $this->buildCategoriesSection($storeId));
        }

        return implode("\n", $lines);
    }

    /**
     * Build CMS Pages section
     */
    private function buildCmsPagesSection(?int $storeId = null): array
    {
        $lines = [];
        $lines[] = '## CMS Pages';
        $lines[] = '';

        $collection = $this->cmsPageCollectionFactory->create();
        $collection->addFieldToFilter('is_active', 1);

        if ($storeId) {
            $collection->addStoreFilter($storeId);
        }

        $maxPages = $this->config->getMaxCmsPages($storeId);
        if ($maxPages > 0) {
            $collection->setPageSize($maxPages);
        }

        $baseUrl = $this->config->getBaseUrl($storeId);

        foreach ($collection as $page) {
            $title = $page->getTitle();
            $identifier = $page->getIdentifier();
            $metaDescription = $page->getMetaDescription();
            $url = $baseUrl . $identifier;

            $lines[] = '- [' . $title . '](' . $url . ')';
            if ($metaDescription) {
                $lines[] = '  > ' . $this->truncateText($metaDescription, 200);
            }
        }

        $lines[] = '';
        return $lines;
    }

    /**
     * Build Products section
     */
    private function buildProductsSection(?int $storeId = null): array
    {
        $lines = [];
        $lines[] = '## Products';
        $lines[] = '';

        $collection = $this->productCollectionFactory->create();
        $collection->addAttributeToSelect(['name', 'url_key', 'short_description', 'meta_description']);

        if (!$this->config->includeDisabledProducts($storeId)) {
            $collection->addAttributeToFilter('status', \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
        }

        $collection->addAttributeToFilter('visibility', ['neq' => \Magento\Catalog\Model\Product\Visibility::VISIBILITY_NOT_VISIBLE]);

        if ($storeId) {
            $collection->addStoreFilter($storeId);
        }

        $maxProducts = $this->config->getMaxProducts($storeId);
        if ($maxProducts > 0) {
            $collection->setPageSize($maxProducts);
        }

        $baseUrl = $this->config->getBaseUrl($storeId);

        foreach ($collection as $product) {
            $name = $product->getName();
            $urlKey = $product->getUrlKey();
            $url = $baseUrl . $urlKey . '.html';

            $lines[] = '- [' . $name . '](' . $url . ')';

            $description = $product->getMetaDescription() ?: $product->getShortDescription();
            if ($description) {
                $lines[] = '  > ' . $this->truncateText(strip_tags($description), 200);
            }
        }

        $lines[] = '';
        return $lines;
    }

    /**
     * Build Categories section
     */
    private function buildCategoriesSection(?int $storeId = null): array
    {
        $lines = [];
        $lines[] = '## Categories';
        $lines[] = '';

        $collection = $this->categoryCollectionFactory->create();
        $collection->addAttributeToSelect(['name', 'url_key', 'description', 'meta_description']);
        $collection->addAttributeToFilter('is_active', 1);
        $collection->addAttributeToFilter('level', ['gt' => 1]); // Exclude root categories

        if ($storeId) {
            $collection->setStoreId($storeId);
        }

        $maxCategories = $this->config->getMaxCategories($storeId);
        if ($maxCategories > 0) {
            $collection->setPageSize($maxCategories);
        }

        $baseUrl = $this->config->getBaseUrl($storeId);

        foreach ($collection as $category) {
            $name = $category->getName();
            $urlKey = $category->getUrlKey();
            $url = $baseUrl . $urlKey . '.html';

            $lines[] = '- [' . $name . '](' . $url . ')';

            $description = $category->getMetaDescription() ?: $category->getDescription();
            if ($description) {
                $lines[] = '  > ' . $this->truncateText(strip_tags($description), 200);
            }
        }

        $lines[] = '';
        return $lines;
    }

    /**
     * Write content to llms.txt file in pub directory
     */
    private function writeFile(string $content): void
    {
        $pubDirectory = $this->filesystem->getDirectoryWrite(DirectoryList::PUB);
        $pubDirectory->writeFile(self::LLMS_TXT_FILENAME, $content);
    }

    /**
     * Get file path
     */
    public function getFilePath(): string
    {
        $pubDirectory = $this->filesystem->getDirectoryRead(DirectoryList::PUB);
        return $pubDirectory->getAbsolutePath(self::LLMS_TXT_FILENAME);
    }

    /**
     * Check if file exists
     */
    public function fileExists(): bool
    {
        $pubDirectory = $this->filesystem->getDirectoryRead(DirectoryList::PUB);
        return $pubDirectory->isExist(self::LLMS_TXT_FILENAME);
    }

    /**
     * Get file modification time
     */
    public function getFileModificationTime(): ?string
    {
        if (!$this->fileExists()) {
            return null;
        }

        $filePath = $this->getFilePath();
        $timestamp = filemtime($filePath);

        return $timestamp ? $this->dateTime->gmtDate('Y-m-d H:i:s', $timestamp) : null;
    }

    /**
     * Get file URL
     */
    public function getFileUrl(?int $storeId = null): string
    {
        return $this->config->getBaseUrl($storeId) . self::LLMS_TXT_FILENAME;
    }

    /**
     * Format description text
     */
    private function formatDescription(string $text): string
    {
        $text = strip_tags($text);
        $text = preg_replace('/\s+/', ' ', $text);
        return trim($text);
    }

    /**
     * Truncate text to specified length
     */
    private function truncateText(string $text, int $maxLength): string
    {
        $text = $this->formatDescription($text);

        if (strlen($text) <= $maxLength) {
            return $text;
        }

        return substr($text, 0, $maxLength - 3) . '...';
    }
}
